global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: transaction-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - transaction-service:8080

  - job_name: fraud-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - fraud-service:8081
