apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-system-config
  namespace: fraud-system
data:
  DB_URL: jdbc:postgresql://postgres:5432/fraud_db
  DB_USERNAME: fraud_user
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_TRANSACTIONS: transactions
  KAFKA_TOPIC_FRAUD_DECISIONS: fraud-decisions
  KAFKA_CONSUMER_GROUP_TRANSACTION: transaction-service-group
  KAFKA_CONSUMER_GROUP_FRAUD: fraud-service-group
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ML_SERVICE_BASE_URL: http://ml-service:8000
  ML_SERVICE_PREDICT_PATH: /predict
  ML_SERVICE_TIMEOUT_MS: "700"
  APP_CORS_ALLOWED_ORIGINS: https://fraud.local
  APP_SECURITY_JWT_ISSUER: fraud-service
  APP_SECURITY_JWT_ISSUER_TRANSACTION: transaction-service
  APP_SECURITY_JWT_TTL_MINUTES: "60"
