apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraud-system-ingress
  namespace: fraud-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fraud.local
        - transaction.fraud.local
      secretName: fraud-system-tls
  rules:
    - host: fraud.local
      http:
        paths:
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /api/v1/dashboard
            pathType: Prefix
            backend:
              service:
                name: fraud-service
                port:
                  number: 8081
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: fraud-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-dashboard
                port:
                  number: 3000
    - host: transaction.fraud.local
      http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /api/v1/transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
