apiVersion: v1
kind: Secret
metadata:
  name: fraud-system-secrets
  namespace: fraud-system
type: Opaque
stringData:
  DB_PASSWORD: change-me
  APP_SECURITY_JWT_SECRET: replace-with-32-char-minimum-random-secret
  APP_SECURITY_ADMIN_PASSWORD: replace-admin-password
  APP_SECURITY_ANALYST_PASSWORD: replace-analyst-password
